development:
  admin:
    - mjgiarlo@stanford.edu
    - jrudder@email.unc.edu
    - steve.vantuyl@oregonstate.edu
    - chris-diaz@northwestern.edu
    - shlake@virginia.edu
    - hparekh@nd.edu
    - gamontoya@ucsd.edu
    - rkati@email.unc.edu
    - jrc88@cornell.edu
    - elr37@cornell.edu
    - shanita@curationexperts.com
    - bess@curationexperts.com
    - mark@curationexperts.com
    - tom@curationexperts.com
    - jamie@curationexperts.com
    - valerie@curationexperts.com
    - cjcolvar@indiana.edu
    - brian.mcbride@utah.edu
    - kmusio@artic.edu
    - johannes.frenzel@rub.de
    - eporter@emory.edu
    - naw4t@virginia.edu
    - saidulla@iu.edu
    - adam.arling@northwestern.edu 
    - moira.downey@duke.edu
    - nikdragovic@gmail.com
    - lrobins5@nd.edu
production:
  admin:
    - mjgiarlo@stanford.edu
    - jrudder@email.unc.edu
    - steve.vantuyl@oregonstate.edu
    - chris-diaz@northwestern.edu
    - shlake@virginia.edu
    - hparekh@nd.edu
    - shanita@curationexperts.com
    - gamontoya@ucsd.edu
    - rkati@email.unc.edu
    - jrc88@cornell.edu
    - elr37@cornell.edu
    - shanita@curationexperts.com
    - bess@curationexperts.com
    - mark@curationexperts.com
    - tom@curationexperts.com
    - jamie@curationexperts.com
    - valerie@curationexperts.com
    - cjcolvar@indiana.edu
    - brian.mcbride@utah.edu
    - kmusio@artic.edu
    - johannes.frenzel@rub.de
    - eporter@emory.edu
    - naw4t@virginia.edu
    - saidulla@iu.edu
    - adam.arling@northwestern.edu 
    - moira.downey@duke.edu
    - nikdragovic@gmail.com
    - lrobins5@nd.edu
test:
  archivist:
    - archivist1@example.com
    - archivist2@example.com
    - leland_himself@example.com
  admin_policy_object_editor:
    - archivist1@example.com
  donor:
    - donor1@example.com
    - leland_himself@example.com
  researcher:
    - archivist1@example.com
    - researcher1@example.com
  patron:
    - patron1@example.com
    - leland_himself@example.com
